#!/bin/bash

# Executes at build-time at dockerhub, and is triggered when a 
# commit is pushed to github.

# Adds "dev" as build-arg for qed Dockerfile, but only if git branch is "dev":
# test "$1" = 'rpi' && (echo "hey")  # this conditional version worked!

# The below conditional works after adding spaces between [ and ]:
# if [ "$1" = 'rpi' ]; then
# 	echo "hey"
# fi

if [ "$SOURCE_BRANCH" = 'rpi' ]; then
	docker build --build-arg port=3000 -t popenc/projects:testing
fi

#docker build --build-arg port=4001 -t popenc/projects:$SOURCE_BRANCH .